import { upsertCollection } from "app/models/collection.server";
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function seed() {
  const address = "0xdB50cd8FE160422F05C2Bd239895752d0493F92c";

  // cleanup the existing database
  await prisma.wallet.delete({ where: { address } }).catch(() => {
    // no worries if it doesn't exist yet
  });

  await prisma.wallet.create({
    data: {
      address,
    },
  });

  await upsertCollection(
    "Devs for Revolution",
    "Devs for Revolution grants token holders official DD Membership",
    "https://lh3.googleusercontent.com/6Jbode0t_bTO9MHYoYvjIW9nHENCxOs40EGg3Z5ptg4lLlD2z2WXEAIrjyV929aQnIi94hPL4VZ3Pl2NWOO_tSaO6gdjdrcMHrF9=s168",
    "0x25ed58c027921e14d86380ea2646e3a1b5c55a8b",
    "ethereum"
  );

  await upsertCollection(
    "Buildspace",
    "If you're a developer curious about NFTs, this is perfect. Programmatically generate your own NFT collection, write + deploy a smart contract in Solidity, and build your own React dApp to let friends connect their wallets and interact w/ your NFTs",
    "https://lh3.googleusercontent.com/WIGvcE3PYeYevgDsfuPooo70pNk0YM5vrXnxmbdWI5iqowpVIkNC1iQKLvA5oUIrnYVG9t6lkzNEj1QvxpBShMT3qmstb8EGZ6Q9yA=s168",
    "0x3cd266509d127d0eac42f4474f57d0526804b44e",
    "polygon"
  );

  await upsertCollection(
    "Doodles",
    "A community-driven collectibles project featuring art by Burnt Toast. Doodles come in a joyful range of colors, traits and sizes with a collection size of 10,000. Each Doodle allows its owner to vote for experiences and activations paid for by the Doodles Community Treasury.",
    "https://lh3.googleusercontent.com/7B0qai02OdHA8P_EOVK672qUliyjQdQDGNrACxs7WnTgZAkJa_wWURnIFKeOh5VTf8cfTqW3wQpozGedaC9mteKphEOtztls02RlWQ=s168",
    "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
    "ethereum"
  );

  await upsertCollection(
    "Goblin Town",
    "AAAAAAAUUUUUGGGHHHHH gobblins goblinns GOBLINNNNNNNNns wekm ta goblintown yoo sniksnakr DEJEN RATS oooooh rats are yummmz dis a NEFTEEE O GOBBLINGS on da BLOKCHIN wat? oh. crustybutt da goblinking say GEE EMMM DEDJEN RUTS an queenie saay HLLO SWEATIES ok dats all byeby",
    "https://lh3.googleusercontent.com/cb_wdEAmvry_noTfeuQzhqKpghhZWQ_sEhuGS9swM03UM8QMEVJrndu0ZRdLFgGVqEPeCUzOHGTUllxug9U3xdvt0bES6VFdkRCKPqg=s168",
    "0xbce3781ae7ca1a5e050bd9c4c77369867ebc307e",
    "ethereum"
  );

  await upsertCollection(
    "Sorare",
    "Sorare is a fantasy football game where managers can trade official digital collectibles. The platform is growing fast, with a global audience collecting, buying, and selling their favorite players in the form of blockchain-backed NFTs. The Sorare team has secured the rights to European giants like Atletico Madrid, Juventus, and Bayern Munich, as well as the MLS, Korean League, and Japanese League.",
    "https://lh3.googleusercontent.com/gj47nmAR3valkmpVbwamiuTJfWEWSCyVeORdjM6DRWrZ1o8WaqBxFXmpBrzZnGoWaPwq1Y0jiXRrBLbnLcawAp92=s168",
    "0x629a673a8242c2ac4b7b8c5d8735fbeac21a6205",
    "ethereum"
  );

  await upsertCollection(
    "Bball Pandas",
    "B-ball Pandas is a NFT collection of 10,000 basketball playing Pandas competing in the blockchain for supremacy. Each Panda is unique and algorithmically generated by combining 100+ traits. B-ball Pandas are each assigned basketball skills that will help you to compete in the interactive game.",
    "https://lh3.googleusercontent.com/chhwE8S6Gt7dh73x5oGfTRu79CO-0P3vQ2UHokRoRGr8FNKPgnK4tS-dDdjWT_vA14L3Rd1vwnkYdbPQ4i3-LhDTVqBQNx91TWQlFQ=s168",
    "0x56c707414bc4c9d3fd71a19d3c266295cf7f7312",
    "ethereum"
  );

  console.log(`Database has been seeded. 🌱`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
