-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."spaces" add column "blockchain" text
--  not null default 'ETH';
